FROM tailscale/tailscale:latest

# Install iptables
RUN apk add --no-cache iptables

# Copy a custom startup script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
